### ISSUE TITLE
Problem with a preseeded admin account credentials

### ISSUE THREAD

**Issue by cesar-xyz** [primeroIMS/primero#145]
Hello Team.

I have tried to be able to log in with the **primero/primer0!** credentials, but it tells me they are incorrect. Is there any way to create an admin account in the terminal or are there any new credentials?

**Comment by cesar-xyz** [comment]
We needed to have a certificate and with the new update the error was solved.

**Comment by jinsthomas** [comment]
Hello @cesar-xyz I am getting the issue for the latest release [v2.5.3](https://github.com/primeroIMS/primero/releases/tag/v2.5.3).

 i did set-up a certificate also in my localhost in mac using mkcert, but still getting the invalid user issue, what could be the reason.

**Comment by roicort** [comment]
I was getting the same issue in [v2.5.2](https://github.com/primeroIMS/primero/releases/tag/v2.5.2) the rake seeding task failed so I was unable to login as any credentials (including default) where in the db. Updated to latest ([v2.5.3.1]https://github.com/primeroIMS/primero/releases/tag/v2.5.3.1) and this was solved.
